import Footer from '@/components/Footer';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'WebDev | The web development',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='bg-gradient-to-br from-cyan-600/20 to-cyan-300/30 flex flex-col min-h-screen'>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
